//! Build script: embeds web/dist/* into the binary as a static byte map.
//! If web/dist is empty or missing, the binary serves files from disk at runtime.

use std::{
    collections::BTreeMap,
    fs,
    path::Path,
    io::Write,
};

fn main() {
    let dist = Path::new("web/dist");

    // Tell cargo to re-run if frontend changes
    println!("cargo:rerun-if-changed=web/dist");
    println!("cargo:rerun-if-changed=build.rs");

    let mut entries: BTreeMap<String, Vec<u8>> = BTreeMap::new();

    if dist.exists() && dist.is_dir() {
        collect_files(dist, dist, &mut entries);
    }

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("embedded_assets.rs");
    let mut f = fs::File::create(&dest).unwrap();

    writeln!(f, "/// Embedded frontend assets generated by build.rs").unwrap();
    writeln!(f, "static EMBEDDED_ASSETS_DATA: &[(&str, &[u8])] = &[").unwrap();

    for (key, bytes) in &entries {
        write!(f, "    ({:?}, &[", key).unwrap();
        for (i, b) in bytes.iter().enumerate() {
            if i > 0 { write!(f, ",").unwrap(); }
            write!(f, "{}", b).unwrap();
        }
        writeln!(f, "]),").unwrap();
    }

    writeln!(f, "];").unwrap();

    writeln!(f, "
pub struct EmbeddedAssets;

impl EmbeddedAssets {{
    pub fn get(&self, key: &str) -> Option<&'static [u8]> {{
        EMBEDDED_ASSETS_DATA.iter()
            .find(|(k, _)| *k == key)
            .map(|(_, v)| *v)
    }}
}}

pub static EMBEDDED_ASSETS: EmbeddedAssets = EmbeddedAssets;
").unwrap();

    println!("cargo:warning=Embedded {} frontend files", entries.len());
}

fn collect_files(base: &Path, dir: &Path, out: &mut BTreeMap<String, Vec<u8>>) {
    let Ok(entries) = fs::read_dir(dir) else { return };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_files(base, &path, out);
        } else if path.is_file() {
            let rel = path.strip_prefix(base).unwrap();
            let key = rel.to_str().unwrap().replace('\\', "/");
            if let Ok(bytes) = fs::read(&path) {
                // Skip empty placeholder
                if key == "index.html" && bytes == b"<!DOCTYPE html><html><head><title>Vane</title></head><body>Loading...</body></html>" {
                    return;
                }
                out.insert(key, bytes);
            }
        }
    }
}
